### ISSUE TITLE
Review of "Strings with paste and glue and stringr"

### ISSUE THREAD

**Issue by michael-chong** [RohanAlexander/DoSStoolkit#1]
Bigger suggestions:

- [x] Might help to see the `stringr` functions used in  a dataframe, since this is a prompt in the exercises. 

Minor suggestions:

- [ ] ~could get rid of package loading messages when calling `library(glue)`~
- [x] "tool-kit" to "toolkit"
- [x] the explanation for `glue_data()` could be simpler/streamlined? Most notably I think it's missing that the curly-brace arguments are filled in with _column names_ instead of _variable names_
- [x] the period-pipe syntax in the `str_detect()` and `str_replace()` examples is unnecessary -- maybe it would be clearer if it was just written plainly like `str_detect(my_vec, ...)`?
- [x] for Exercise 2, the solution might be easier to read with pipe syntax

**Comment by RohanAlexander** [comment]
Hey @mpejcinovska - I think these are in your lesson?
Can you please update what you think needs to be updated and make a pull request?
The code lives in inst/tutorials/
