### ISSUE TITLE
Review of "to ggplot or not to ggplot"

### ISSUE THREAD

**Issue by yenajoo** [RohanAlexander/DoSStoolkit#11]
60: ggplot2::ggplot()
- [x]  Handy layers: “Legend” and  “Faceting” parts are empty. Incomplete? 

61: Bar charts
- [x] Under the “Exercises” part: For the multiple questions, there is only one chance to answer. 

62: histograms 
- [x]  Missing title and author on the top of the template

63: Scatter plots two variables 
- [x]  Incomplete? 

64: Static maps
- [x]  Actually, another lecture (lec #65) is written here…. Should I delete the existing content? 

65: Various useful options
- [x]  This is my part. I Will finish up soon 

If I find more errors in the future they will be updated

**Comment by HaoluanChen** [comment]
62: histograms - added title and author 

63 63: Scatter plots two variables - It is finished and pushed. Let me know if there is any problem. Thank you

**Comment by michael-chong** [comment]
Could you elaborate on what you mean about 64/65?

**Comment by yenajoo** [comment]
@HaoluanChen I think everything looks good. Thank you

@michael-chong another lecture was written on the lec 64 document, now it is replaced with the correct lecture. 
And for 65 I was in charge of writing the lecture at that time it was incomplete

**Comment by RohanAlexander** [comment]
I'll close for now. @yenajoo feel free to re-open if you think there's still an outstanding, or make a new issue.
