### ISSUE TITLE
Review of "RMarkdown"

### ISSUE THREAD

**Issue by mpejcinovska** [RohanAlexander/DoSStoolkit#13]
Main issue:

- [x] The submodule seems unfinished; or at least the "Math" and "Code" sections seem unfinished 

Additional suggestions: 

- [x] The first bullet point in `output:pdf_document` should be `output:html_document`?
- [x] In the "Superscript" subsection replace _underscore_ with _caret_
- [x] "WHY ISN'T IT NUMBERED?" is just sitting there after the first equation is introduced. Was it meant for this to be there? In theory, invoking `\begin{equation}` should number it (the `amsmath` package should be part of the template (??)), but if not you could try `\begin{align}` or add the package in the YAML maybe (`\usepackage{amsmath}`)

**Comment by RohanAlexander** [comment]
@mpejcinovska I know that Shirley isn't too comfortable on GitHub so may not have seen these, but when I have a look it looks like they're all addressed.
Feel free to re-open or create a new issue if you think think I missed something.
