### ISSUE TITLE
Review of "Tables: kable, kableextra, gt"

### ISSUE THREAD

**Issue by mpejcinovska** [RohanAlexander/DoSStoolkit#14]
Few issues: 

- [x] Not sure if this was intended but tables don't render too well in the html output online (for instance, the two tables side by side example makes the tables look jammed together)
- [x] The part "In this lesson, you will learn how to:" needs formatting, so that you have a list of items students will learn. At the moment the list is sort of inline. 
- [x] In the subsection "Arguments of `kable()`" it might be helpful to list out those argument and give a brief description what each does. 

Some minor stuff

- [x] commented out code that is not relevant to the lesson should probably be removed (for example `#kbl(head(mtcars))` isn't mentioned as the alternative way to run the table so might be confusing)
- [x] paragraph after the gt table image needs formatting. It starts to the right of the image instead of on a new line

**Comment by michael-chong** [comment]
Most of this looks like it's been addressed. @mpejcinovska are the side-by-side tables still an issue?

**Comment by RohanAlexander** [comment]
@mpejcinovska can you please just have a quick check when you have time. I'm not quite sure about the problem.

**Comment by mpejcinovska** [comment]
Looks good! Thanks @yenajoo. I'm closing this issue.
