### ISSUE TITLE
Review of "References and Bibtex"

### ISSUE THREAD

**Issue by mpejcinovska** [RohanAlexander/DoSStoolkit#15]
It might be good to build up a bit more of the content in this submodule. 

For instance, 
- [x] could consider explaining what a .bib file is. And that one needs to be placed in the YAML of the document...
- [x] could give an example of what such a bib file looks like with 2-3 basic citations in it and then tie that to the example you give later on about how to refer to specific references from your bib file. This way it might be easier for students to understand the key used to call a reference and where it comes from. 
- [x] perhaps consider adding a line or two about why citing R packages matters before you jump into the citation function. You could speak to the need for reproducibility here.

**Comment by michael-chong** [comment]
These look like they've been addressed. Thanks @mpejcinovska and @yenajoo!
