### ISSUE TITLE
Review of "length(), nrow() and ncol()"

### ISSUE THREAD

**Issue by michael-chong** [RohanAlexander/DoSStoolkit#3]
- [ ] I think `secret_matrix` is not accessible in the exercises? I get an error that `secret_matrix` is not found. ![image](https://user-images.githubusercontent.com/25188455/116172525-f0ead280-a6d8-11eb-8c5d-5b30af915e30.png)

- [x] maybe want to include `dim()`, since this might be handy if working with higher dimensional arrays

Minor issues:

- [x] formatting typo under Arguments > length (need space between `####` and `length()`)
- [x] typo ("contians" -> contains*)

P.S. I love the thought of `length()` returning: _The length (in centimeters) printing a vector will occupy on your screen_

**Comment by RohanAlexander** [comment]
Hi @imehrlich,
Can you please have a look at these and either address them or say why they shouldn't be addressed in a comment here.
Rohan

**Comment by imehrlich** [comment]
Hm, I don't seem to be getting an error with secret_matrix when I'm running it locally - does this error pop up when working through the package? The matrix is created in a code chunk directly above the exercise.

Added in the other edits.

**Comment by RohanAlexander** [comment]
I'll close this for now. We can always revisit it later if returns.
