### ISSUE TITLE
Connection refused in RStudio Cloud

### ISSUE THREAD

**Issue by eijoac** [RohanAlexander/DoSStoolkit#35]
Tried to open the very first tutorial "learnr::run_tutorial("hello_world", package = "DoSStoolkit")" in RStudio Cloud.  The pop-up new browser window showed an error "Connection refused". Thanks.

**Comment by RohanAlexander** [comment]
Best we can tell, it's a random issue from time to time with R Studio Cloud, see:
https://community.rstudio.com/t/connection-refused-when-running-learnr-modules-on-rstudio-cloud/105817
Could you please try again later and see if the issue persists. When I had the issue it disappeared the next day.
