### ISSUE TITLE
Review of "set.seed(), runif(), rnorm() and sample()"

### ISSUE THREAD

**Issue by michael-chong** [RohanAlexander/DoSStoolkit#5]
- [x] include discussion for the `prob` argument for `sample()`
- [x] The distinction between sampling with and without replacement isn't totally clear in the example given. Maybe set a seed such that we can see repeats in the `replace = TRUE` result?
- [ ] In the `set.seed()` example, I get an error saying that `x` is not found:
![image](https://user-images.githubusercontent.com/25188455/116175054-99029a80-a6dd-11eb-8e41-917430852b6f.png)

- [x] add a question mark to Exercise 7, maybe clarify wording to: "How would you ensure that the simulations in Exercises 4 and 5 give the same result every time?"

**Comment by HaoluanChen** [comment]
Everything is fixed and updated! thank you for your comments
