### ISSUE TITLE
Review of "Hello world!"

### ISSUE THREAD

**Issue by anniecollins** [RohanAlexander/DoSStoolkit#7]
"Getting and Setting up R Studio"
- [x] Formatting under "Introductions" is a bit weird (bullets not showing up correctly; can update with new lessons 01/02)

"Hello world!"
- [x] Text under summary stats does not match up (Annie messed up and recorded the summary stats for an earlier time frame than the current data

"Hello world, again!"
- [x] In "Promo Code Discount vs. Order Total" graph, axes should be switched based on intro, ie. change code to ggplot(aes(x=promo_percent, y=order_total))..., rest should still be valid

"The R community"
- [x] The R Weekly YouTube channel is not great and also inactive, might just be worth removing
- [x] Under R Meetups, first bullet point is redundant and also missing a URL; remove

"Summary and next steps": 
- [x] Would it be worth including code to access the next module here, or a link back to the website? Should be kept consistent across all modules either way I would assume

**Comment by michael-chong** [comment]
For this chunk in "Hello world, again!", I think the axis labels are mixed up?

```
scatter <- 
  orders %>% 
  ggplot(aes(x=promo_percent, y=order_total)) +
  geom_point(color = "#1b9e77", fill = "#1b9e77") +
  ggtitle("Promo Code Discount vs. Order Total") +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Order Total") + ylab("Promo Code Discount")

scatter
```

**Comment by michael-chong** [comment]
Everything looks like it's been dealt with. Thanks @anniecollins!
