### ISSUE TITLE
Review of "Totally addicted to base"

### ISSUE THREAD

**Issue by anniecollins** [RohanAlexander/DoSStoolkit#8]
"mean(), median(), sd(), lm(), summary()"
- [x] Exercise 2 returns "object 'broadway' not found" (although maybe this isn't the biggest issue since the output is not particularly important for the question)

"for() and while()"
- [x] Under "What are Loops?" it says "insert pics"
- [x] format of bullets is also a bit messed up under "You can iterate through"
- [x] last sentence before "while() loop" cuts off
- [x] this might be too picky, but MCQ Question 1 might give someone who is new to for-loops the indication that for-loops and indexing are interchangeable, or that for-loops loop over indexes and not the actual values of a object
- [x] Question 2 doesn't give the name of the data frame, and when the solution is run it returns "object 'members' not found"
- [x] Question 4 has description but no question
- [x] Under "Common Mistakes & Errors" I think the first point is intended to communicate a common mistake but it sounds like an instruction. The second point could use some clarification as well.

"c(), seq(), seq_along() & rep()"
- [x] under "Highlights", third point incomplete
- [x] Under "Common Mistakes & Errors", it looks like the bullets/formatting is messed up

"Summary, and next steps"
- [x] Incomplete?

**Comment by mwalaa** [comment]
Thank you! So weird, I needed to load tidyverse before loading the data (twice, not only in the setup code chunk). I didn't notice that before, thanks!

**Comment by michael-chong** [comment]
@yenajoo I believe there are some outstanding points with the "for() and while()" lesson

**Comment by RohanAlexander** [comment]
This seems fine to me now?
