### ISSUE TITLE
Review of "Hand me my Plyrs"

### ISSUE THREAD

**Issue by matthewwankiewicz** [RohanAlexander/DoSStoolkit#9]
I'm not sure if it was an issue on my end but data that already existed as part of R or is an R package like `penguins`, `quakes` or `starwars` ran fine without error in the chunk where users can code on their own. But it seemed like errors occurred when the data was created/manipulated outside of that practice chunk (like getting the data from a website or making your own data).

Introduction
- [x] It seems like the link for the baseball example is broken.

"The Pipe"
- [x] For the exercises it seems like the solution isn't working. When I type in the exact answer it marks it incorrect and says "object ‘ex1_sol’ not found". This happens for the other exercise as well.

"Select"
- [x] For question 2 in "Exercises" it says "object 'temperature_data' not found".
- [x] For question 4 it says "object 'child_book_data' not found" when trying to run the exercise.

"Filter"
- [x] For the exercises section it gives the error "object 'guineas' not found".

"Summarise"
- [x] Getting the error "object 'broadway' not found" for the exercises. 

"Mutate"
- [x] For the exercises I'm getting the "object 'scores' not found" error and the "object 'final' not found" error. 

"Pivot wider and Pivot longer"
- [x] Got error "object 'games' not found"..

"Rename"
- [x] "object 'personalities' not found" for the first exercise.

"Count and Uncount"
- [x] The code for the multiple-choice questions isn't hidden so users can get the answers from the code. Same thing for the exercises where you need to replicate the dataset shown.

"Slice"
- [x] For "Omitting rows" section the error "object 'pizza' not found" occurs.
- [x] In the "Questions and Exercises" section under "Questions", the code isn't hidden for the multiple-choice questions.
- [x] Exercises give error "object 'olympics' not found". When I copied the code that made the Olympics data into the code chunk and then answered it avoided that error.

**Comment by mwalaa** [comment]
The issue seems to be fixed if we just load tidyverse separately before we load that data (so we load tidyverse outside of the setup code chunk as well). I've fixed it for summarise, rename, pipe. Thanks!

**Comment by HaoluanChen** [comment]
Not found errors should be fixed for mutate! Thank you

**Comment by michael-chong** [comment]
Went through and checked off stuff that looks done.
I think the only thing left for this issue is the link to the baseball example in the introduction? @RohanAlexander

**Comment by RohanAlexander** [comment]
All done. Thank you very much @michael-chong @mwalaa @HaoluanChen and @matthewwankiewicz !
